### ISSUE TITLE
Generating Coverage Values with Rosella

### ISSUE THREAD

**Issue by aljazdzy** [rhysnewell/rosella#39] opened 2023-07-10 20:41 UTC
Hello!  I was attempting to generate MAGs and coverage values using Rosella but the Useage page says this is what the command structure for that should look like, 

rosella bin -r scaffolds.fasta -1 short_s[12345].1.fastq.gz -2 short_s[12345].2.fastq.gz --longreads nanopore.fastq.gz -o rosella_bins/

As has been noted elsewhere, bin is no longer a command and I should really be using recover.  But when I run recover I get: 

USAGE:
    rosella recover --base-quality-threshold <base-quality-threshold> --contig-end-exclusion <contig-end-exclusion> --kmer-size <kmer-size> --longread-mapper <longread-mapper> --mapper <mapper> --mapq-threshold <mapq-threshold> --method <method> --min-bin-size <min-bin-size> --min-contig-size <min-contig-size> --min-covered-fraction <min-covered-fraction> --min-read-aligned-percent <min-read-aligned-percent> --min-samples <min-samples> --n-neighbors <n-neighbors> --output-directory <output-directory> --reference <reference> --threads <threads> --trim-max <trim-max> --trim-min <trim-min>

But none of these commands align with what is happening in the line from the useage page.  It also keeps telling me I need a reference file, I'm a little uncertain, does Rosella use its own set of reference files? What exactly is going on here? 

If I run: 

rosella recover -r final.contigs.fa --longreads pass_Green2022_Depth19.fastq.gz --output-directory Output

I get: 

[2023-07-10T20:29:21Z INFO  rosella] rosella version 0.4.2
[2023-07-10T20:29:21Z INFO  rosella] Using min-covered-fraction 0%
[2023-07-10T20:29:21Z INFO  rosella] Using min-read-aligned-percent 0%
[2023-07-10T20:29:21Z WARN  rosella::estimation::contig] ERROR: User has not supplied reads, BAM files, coverage results or directory containing results of previous run. Cannot proceed. Exiting...

But I guess I'm confused because I don't have coverage results, a previous run, or BAM files from a previous run, so why is it asking for this? I have reads in fastq format, and maybe I can conjure up some other information, but wouldn't this be generated while running? 

Any help would be greatly appreciated!

**Comment by rhysnewell** [comment] 2023-07-10 22:23
Hey there,

thanks for trying out `rosella` looks like something odd is happening. Judging from the the second error, it looks like maybe the paths for your input files might be a little off? If you run `ls` on each of the input files from where you were trying to run rosella, does the command fail?

I'm just thinking that maybe the files might be sitting up or down directory from where you currently are. So that could be assembly file, the longreads, and the short reads.

Then I'd check if the output directory already exists, and make sure it doesn't have anything in it

Cheers,
Rhys

**Comment by aljazdzy** [comment] 2023-07-10 22:30
Thanks I'll try that, can rosella just do long reads or does it need associated short reads?

**Comment by rhysnewell** [comment] 2023-07-10 22:54
It should be able to run with just long reads, but if you have any problems with that let me know and I'll fix it up

**Comment by aljazdzy** [comment] 2023-07-10 22:57
I double checked the directories but all the files are where they should be.  I also tried this: 

rosella recover -r final.contigs.fa -1 pass_Green2022_Depth19.fastq.gz --output-directory Output

Just to see what would happen, but of course it told me I need another read file (-2) , which I did find kind of curious, is this telling me I need to have multiple files to run the program? I have others from the same lake which would hypothetically have some of the same organisms, but for a first run I thought I'd try just a single file.  

I appreciate your time, I'm excited to generate some MAG's with this program!

**Comment by aljazdzy** [comment] 2023-07-10 23:04
> It should be able to run with just long reads, but if you have any problems with that let me know and I'll fix it up

Ok awesome!  Just uh, just because I'm admittedly quite new at some of these bioinformatics pipelines, am I close to doing the correct input structure  you would expect for the program?  In this scenario final.contigs.fa were contigs generated using a different bioinformatics pipeline (it used megahit to generate contigs) because it was a pipeline designed for a specific set of genes I'm after, and the fastq file is the file that the contigs were generated from.  I'm uncertain if this is the correct set of files that I should be using for this.  Thank you so much!

**Comment by rhysnewell** [comment] 2023-07-10 23:18
No, it just means that if you use the `-1` flag it expects there to be an associated `-2` flag. Hmm, okay so the files exist but do you have read/write access to them? like can you try running `zcat pass_Green2022_Depth19.fastq.gz | head` and does it output the first few reads within the fasta file for each read file?

Maybe if you could also send me a screenshot of the output you get when running `ll` within your current directory?

And yes, don't fret I think you are quite close to getting it to work there is just some minor hiccup occurring that we can fix. Yep, you'd run binning on the assembly generated from your reads. Generally a metagenomics pipeline runs like this:
1. QC reads if they haven't been QC'd already e.g. fastqc, nanoplot, trimmomatic
2. Assemble reads with your chosen assembler. In your case this is megahit
3. Map reads used for assembly back on to assembly
    - Some people use multiple different reads from different samples in this step to get a better signal. This is not always necessary
    - This mapping step is also handled by `rosella`. You should be able to take the coverage file it produces and hit it other binners like `metabat`
4. Bin the contigs using a variety of binning programs e.g. rosella, metabat, semibin, graphbin
5. Refine the bins with dastool, rosella, or graphbin(?)
6. QC the bins

So you've got your assembly and you've almost generated some bins. I would strongly recommend using a variety of binning algorithms as each binner sees the contig world a little differently and is capable of pulling out more complete bin sets (see metagenomic binning pipelines like [Aviary](https://github.com/rhysnewell/aviary).

Often these pipelines, like aviary, handle all this busy work for you. So it will run rosella for you and get all the coverage information and QC the bins using all the different programs and try and give you a more collated result. The problem is that it can take a little bit to setup the pipelines like installing all the databases and programs that it needs.

If you are still new to bioinformatics, I'd recommend getting hands on experience with a variety of different tools and then when you have an understanding of how they work and what they are doing maybe switch over to a collated pipeline.

**Comment by aljazdzy** [comment] 2023-07-11 15:53
Yes!  So when I run that code I get the following output: 

@9c070474-e36d-441c-bcea-f613dc63b9b7 runid=68da4558075a25d17a0d1a4de3bff41a2241d38f read=47 ch=303 start_time=2023-06-14T19:44:27.321868-04:00 flow_cell_id=FAX02769 protocol_group_id=GreenLake2022_18_19_20_25_30 sample_id=no_sample barcode=barcode02 barcode_alias=barcode02 parent_read_id=9c070474-e36d-441c-bcea-f613dc63b9b7 basecall_model_version_id=2021-05-17_dna_r9.4.1_minion_96_29d8704b
GTATTACTTCGTTCGGTTATCTGGAGGTGGGTGTTTAACCTCCGATTCCGTTTGTAGTCGTCTGTGTTTTCCGCATTTATCGTGAAACGCTTTCGCGTTTTCGTGCGCCGCTTCATAGTCGTCTGTGTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTT
+
$##**,01<:378:*''-*(%%&'*%%$$(/0147.--5489(''''+'%'3477444466544488<@@B1/73/?AE?>0/,.2<?)'*.()--/36@=:30079==...59<>5556-,&$&..;;?8=&,/444=::-,,241.++,878-013465
@d4c0f346-d55a-4581-bee1-9545ee88e5ac runid=68da4558075a25d17a0d1a4de3bff41a2241d38f read=28 ch=152 start_time=2023-06-14T19:44:24.321868-04:00 flow_cell_id=FAX02769 protocol_group_id=GreenLake2022_18_19_20_25_30 sample_id=no_sample barcode=barcode02 barcode_alias=barcode02 parent_read_id=d4c0f346-d55a-4581-bee1-9545ee88e5ac basecall_model_version_id=2021-05-17_dna_r9.4.1_minion_96_29d8704b
GTATTACCGTTCGGTTACATCAATTTGGGTGTTTAACCTCGATTTCCGTTTGTAGTCGTCTGTGTTTCTTGTTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCACTAACCCACCTGGACAAATGGCATTGGCCCCTTAATCCTTTTGTTGCGTAGTCAGCGCCATTTTTAGTTAAAACCTACGATAGCGTGTTTTGAAGCCACATAAGCTGGTATGCTTTCGAAACCAACTAATCCGGCGACAAATGCAATGTTGATAATAACGCCTGCGCCTTGCTTCAACATCATGGGAATTTCACTTTTCGGCATAAAAAGTACCCGTCAAATTTACATTGGTATGTTGCCAATTTTCTAAGGTACAAGAATCTATGGGACTGCTAACCCCTTCAATGCCTGCATTATTTGTGAAAATCAAGCCTTCATAGTTTTCTCTATGGTTTCCATTAAATGATTTACCTGTTCAACCTTTAGAAACGTCGCATTGTATAAAAATACCGTACCTCCATTTTCTTTATTAAATCTAACGTTTCGAACCGTCTTTAATCGGCAATCACTACTGTGGCCTTGGGCAACAAATGCTAAAGCGGTAGCGGCCAATACCAAAGCTGCCTCCTGTCAGCAAATGAATAAAATTGAAAGTTTGTCGTTTATTTTAACCTGTCTGGATTGTCGCTAAAAAATTTTTTCCAGGTAACTTTTTCTGCTTCTTTACCGGCGTTTTCGTCGTGGATGTACTTATTTTACCATTTTGGTAGAAGTAGCGGAGCTGCAGATAAGCATCGGTAGCATCTAAAAACTGCCCGTTAAATCAACAGCGGCTTTAATAAATGACCTTTGCTCTTTCTTGCATTTCCATTTTCCTGTAACCGATTGCTTTATTTTACGCGGAAGTATTCAAAAATTTCTAATCGCTGTCCGTACCAATAGCCATGGCAACTCCCTGTGCCGGCTTAACGCGCCGTTGAACATTTTTGCGCCAAACGGGCTTCAATAGCCATAATCGTTGGTTTATAAGTATCTATAATACTTTGAAGTCTTTCCAGTATTTTTAATAATCTTGGCAGGATGATCATGGCGCATCTAAAAAATAACACCAATGTCCATTGTTTCATTTGATTTCCATTGATTTCCAATGAATATCATTTTACCGTTCGAGATCGACGCCTAAAATACGGTATGTTTATTTCAGTTAGT
+
%$$%%$#&(-45(%&*('&''&$$%.,.3388;88886690--.3<51;=B/-//12668<///7>?<''&&&457;210.0///0364546401-&&$%%-2143('-4+)*(*)+++''399<??=AID:9:('')((())))+5:3-+999787<=,-,+.-'++((&%&'111/--/%%(+&';::::=/()8337;;>7/<<99750&&)13201325947211((-(()1/--277752'&'-&$$(*+,,3::9:88;7@::@?:555783330988?AH<+++32))('(*.3;=;//0<>?=)%&&'')<<:+((--9889<:;:988434820272327=@@@CBDD?@2-%+01245350&%'/'&((,755;<8=?<<>>?{F7777557376268:<@5.-/44::7655((.0./1699={{{2;6005622034233:9?;7001??974488A2211887337=>8677679?@=:8238;8.(((/././)&31002>@@6E@=:;<?:;A/89><>@A<'.0.+*)()*,-/<;1('(4@<98731.)('**'&&%$&(/&%&=??:111:@?'&+-.-.%'*491.+*))%&&'(')(),)&788+3448>>76:7?@=31010102364%"##%(2*))0222:0/01102//,,-..((*+.1B===@B{{DA)(-4,:551+)&&&*&%''&&23///-./49:?=?<=>889<?>//.40--./56(()**-<=:867''/-,++/)&($%&*(&&6766523><,,,+),-::0)))'((*(3456;<>?576*&%%&'$%$%/,%--.365('&%%)(*+,75;7&&''')/1=@@<AB{;B<;98:?>7655:6359887?></,''%'*'-488<B8<D73BDBD8:999''*'.1(&'(,.43--('()''(+3/.,45.3&&&00,(('&&'-%%054400+(1*246{AE62&&%$)00,+--35/+(.&%$$%&+/88:<@?:/<4-++)'(*026854)($)58676-(''01:=/)2383BAB>=?:6350/.&$'''-4=778<.+)+--./33456<:1610++&('.799<<5))-69>;;567999:91=837798=B?L-,75&&+%'*2**,74++,89;=(&+,.657<987894386,,--.)(%$)534:A?.110)&%
@f03a0349-8912-4199-af6c-1013537d7f86 runid=68da4558075a25d17a0d1a4de3bff41a2241d38f read=60 ch=295 start_time=2023-06-14T19:44:27.321868-04:00 flow_cell_id=FAX02769 protocol_group_id=GreenLake2022_18_19_20_25_30 sample_id=no_sample barcode=barcode02 barcode_alias=barcode02 parent_read_id=f03a0349-8912-4199-af6c-1013537d7f86 basecall_model_version_id=2021-05-17_dna_r9.4.1_minion_96_29d8704b
AGCAGCGCGTTCGATTCAAATTTGGGTGTTTAACCTCGATTCCGTTTGTAGTCGTCTGTGTTTTCGCATTTATCGTGAAACGCTTCGCGTTGCCACTTCAGCCGAGATGAAGCGTTGTCTTGTGCAGGTGTGCGGGTGCTCAACGGCGAAGCCCCGGATGAGACCGACTGGCACCAGCGCCTGTTGGAACATGGCCATTGCCACGGAAGCGCAGCCCGCCGTTTTGGCTGCAGGCACGGTGGGGCGCTTGGGGAGTGCTTTCGCCGTAACGTGGTGCGCCATCTCTATGCCTATGAACTGGAACGAGACCAGGTATTTCGGCTATTGACCAGCGCAATTGGGCTGCGGCCCCAACTGCGTTAGTTTCGACCTTCGGGGCTTGGCTGAACGATTTGAGCGGCCCCGCCTAATTCGACACCTGCTTAACATTCGTTACGAATCAGCCCTGCCGCTGACCGTTGCCCCCAGCCCAGCCGCCGCGCCATCCTTCAACCGCGCCGAATGGGCCAGCGCTTTCAAAACGTGGAACGGGAACTCAGCCAGGTGCCGCTCCGGCAACCCGGGGCGATCCGCCGGAGCTGCTGGAGCACGCTTTATCGCAATGGCCCCGGCCGACTGGGGCAGGGCGGCCGGTATTGCACCACGCTGATGGCGATGGTTTGATCTGTACCCCTGCGCTTTGGGGCCAGGGCCGCCAGCTTCAACCCAACCGCTTGTGCGGGCTGGTTGGCGGAGGAGGCCGCAGGCCGGGTGCTGTACCGCGGCGTGTTTGGCAGCGCTCGCCAGCAGCCCCTGGCCAATGCAGCGGCCTGCGCCTCAAGTGTAGCCCTTTACCCAGGTGGTGCAGCTAGGCGATCAGCTGCTGGCCACGCACAGAGGCCAGTTCCCC

Which I think is probably correct?  Also, what is running 11 exactly?  Pardon my ignorance, also does Aviary then run multiple binners?  Thank you so much for your help.  I have admittedly struggled with getting binners to run, I've also tried Nanophase but have run into errors there as well.  Though the idea of running multiple samples through Rosella has intrigued me, as I'm struggling to get as many reads as I need currently.

**Comment by rhysnewell** [comment] 2023-07-11 22:44
Cool, yeah that's first read in your long read file. So you definitely have read access to the stuff in that directory.
Sorry, not 11 it was ll (lowercase LL) it's shorthand for `ls -aslF` on a lot of linux based machines. Try just typing ls -alF and show me the result please, also just make sure that you have write access within your current directory by running `touch test`

**Comment by aljazdzy** [comment] 2023-07-17 15:08
Ok thanks will do!  Sorry I didn't reply for so long, sampling was last week and that took up my week more-or-less.

**Comment by aljazdzy** [comment] 2023-07-17 15:13
When I type in "ls -alf" in that directory I get:

translations          ..          lib      .crates2.json  plugins  include       fonts  .crates.toml  x86_64-conda-linux-gnu  compiler_compat                  phrasebooks
.                     var         libexec  mkspecs        man      rosella_bins  share  bin           etc                     pass_Green2022_Depth19.fastq.gz
final.contigs.fa.fai  conda-meta  Output   doc            cmake    qml           sbin   ssl           final.contigs.fa        x86_64-conda_cos6-linux-gnu

**Comment by aljazdzy** [comment] 2023-07-21 00:33
Update, I ran, "touch pass_Green2022_Depth19.fastq.gz" which updated the date of the file to the current date, which I believe indicates it is there and that I do have access to it? I think anyway.

**Comment by rhysnewell** [comment] 2023-07-24 05:21
Hey there, sorry for the delay I've just been on leave.

Could you try getting the coverage values with [CoverM](https://github.com/wwood/CoverM) using `coverm contig -r final.contig.fa --single  pass_Green2022_Depth19.fastq.gz -t 16 -m metabat -p minimap2-ont -o coverages.tsv` or something similar, and then pass the `coverages.tsv` file to rosella without the reads.

I think maybe the version of Rosella you are using doesn't allow for nanopore only coverage values. Future versions do and will, if you are feeling experimental you can shift over to the [ISS-36](https://github.com/rhysnewell/rosella/tree/ISS-36) branch to use rosella to generate coverage values but that would be a lot of work. If you are not feeling confident, just use coverm

**Comment by aljazdzy** [comment] 2023-07-24 16:03
Ok, that's good advice!  I'll try it and let you know how it goes.

**Comment by aljazdzy** [comment] 2023-07-26 15:58
So I did as you suggested and it worked!  The issue may have been with the nanopore reads, though I also think it's possible my contigs were an issue as well.  Using coverm it didn't want to initally run with the contigs that were generated, so I used a different assembler and that ended up working.  I may try to run what I was running before and see if it works with the other assembler and then report back.

**Comment by aljazdzy** [comment] 2023-07-26 16:10
I tried it with the new contigs and it is definitely a nanopore specific issue.  But, your previous suggestion worked so I'm going to use that moving forward!  Thank you, and thank you for the time you've taken to help me!  And also for being a co-author on this cool program!

**Comment by rhysnewell** [comment] 2023-07-26 23:22
Cool, glad you could sort it out! I'll go ahead and close this issue, if you have any other questions or problems feel free to contact me or re-open the ticket.

Cheers,
Rhys

**Closed by rhysnewell** 2023-07-26 23:22 UTC

**Comment by aljazdzy** [comment] 2023-08-03 20:10
Thanks Rhys!  I do actually have another question related to coverage: I've been running Rosella and thus far have been pretty impressed with the accuracy of the bins, but as mentioned before I've been doing so by running CoverM first and then using that output for the Rosella run with my contigs.  But the CoverM output often says something like: found 298 reads mapped out of 349978 total (0.09%)

And it's consistently very low numbers like that.  So when I run Rosella it seems to only be using the 298 contigs.  The 349978 number I believe refers to the original read count, not the number of contigs in the contig file I'm using.  The contig file has 997 contigs and flye (the assembler I'm using) has a file in which it has a "coverage" column that has coverages for every contig listed.  This specific depth(sorry, my samples are from depths of a lake so I refer to each sample as a "depth", it is not in reference to the depth of the contigs) should have a significant diversity of organisms but Rosella only created three bins.  Is this the appropriate way to be doing this or should I be trying to use the flye coverage values (which are whole numbers instead of percentages) instead? 

My CoverM output looks something like: 

contigName	contigLen	totalAvgDepth	assembly.fasta/pass_Green_2022_1.fastq.bam	assembly.fasta/pass_Green_2022_1.fastq.bam-var
contig_1	10911	0	0	0
contig_10	3266	0	0	0
contig_100	2693	0	0	0
contig_101	5090	0.0206	0.0206	0.0202
contig_102	3968	0	0	0
contig_103	15482	0	0	0
contig_104	3787	0	0	0
contig_105	4746	0	0	0
contig_106	3709	0	0	0
contig_107	12158	0	0	0
contig_108	6559	0	0	0
contig_109	3613	0	0	0
contig_11	2402	0	0	0
contig_110	6308	0	0	0
contig_111	14652	0	0	0
contig_112	7359	0.0139	0.0139	0.0137
contig_113	17505	0.0247	0.0247	0.1445
contig_114	5500	0.0258	0.0258	0.0251
contig_115	2335	0	0	0
contig_116	27225	0.001	0.001	0.001
contig_117	3105	0	0	0
contig_118	8546	0.0042	0.0042	0.0042
contig_119	6354	0	0	0
contig_12	15407	0	0	0
contig_120	2269	0	0	0
contig_121	2749	0	0	0
contig_122	10920	0.0029	0.0029	0.0029
contig_123	10211	0.0061	0.0061	0.006


While my coverage values for Flye look something like: 

#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
contig_715	147388	6	N	Y	2	*	*,715,*
contig_919	86133	7	N	Y	2	*	*,919,*
contig_710	84424	6	N	Y	1	*	*,710,*
contig_403	67366	7	N	Y	2	*	*,403,*
contig_783	60610	7	N	Y	2	*	*,783,*
contig_169	56091	6	N	Y	2	*	*,169,*
contig_960	55847	6	N	Y	2	*	*,960,*
contig_694	55630	6	N	Y	2	*	*,694,*
contig_603	53445	6	N	Y	1	*	*,603,*
contig_862	47956	6	N	Y	1	*	*,862,*
contig_39	47625	5	N	N	1	*	*,39,*
contig_265	44381	5	N	Y	1	*	*,265,*
contig_791	44126	3	N	N	1	*	*,791,*
contig_316	43721	6	N	Y	1	*	*,316,*
contig_211	43689	3	N	N	1	*	*,211,*
contig_726	40851	6	N	Y	2	*	*,726,*
contig_478	40671	6	N	Y	1	*	*,478,*
contig_948	38604	6	N	Y	1	*	*,948,*
contig_128	38040	6	N	Y	2	*	*,128,*
contig_591	36783	6	N	Y	1	*	*,591,*
contig_256	35667	5	N	Y	1	*	*,256,*
contig_847	35349	4	N	N	1	*	*,847,*
contig_751	35248	5	N	Y	1	*	*,751,*
contig_972	33308	6	N	Y	1	*	*,972,*
contig_70	33153	6	N	Y	1	*	*,70,*
contig_200	31281	3	N	N	1	*	*,200,*
contig_967	30010	6	N	Y	2	*	*,967,*
contig_8	29840	4	N	N	1	*	*,8,*
contig_775	29831	4	N	N	1	*	*,775,*
contig_390	29133	7	N	Y	2	*	*,390,*
contig_725	28636	5	N	Y	1	*	*,725,*
contig_767	28289	4	N	N	1	*	*,767,*
